//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuota
    {
        public int id { get; set; }
        public int municipalidad_id { get; set; }
        public Nullable<int> banco_id { get; set; }
        public Nullable<decimal> intereses { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<decimal> importe_abonado { get; set; }
        public Nullable<System.DateTime> vencimiento { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha { get; set; }
        public string forma_pago { get; set; }
    
        public virtual banco banco { get; set; }
        public virtual municipalidad municipalidad { get; set; }
    }
}
