//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuotasEntities : DbContext
    {
        public CuotasEntities()
            : base("name=CuotasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<banco> bancos { get; set; }
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<inventario> inventarios { get; set; }
        public virtual DbSet<inventario_foto> inventario_foto { get; set; }
        public virtual DbSet<municipalidad> municipalidades { get; set; }
        public virtual DbSet<oficina> oficinas { get; set; }
        public virtual DbSet<perfil> perfiles { get; set; }
        public virtual DbSet<proveedor> proveedores { get; set; }
        public virtual DbSet<subcategoria> subcategorias { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<compra> compras { get; set; }
        public virtual DbSet<cuota> cuotas { get; set; }
        public virtual DbSet<ingreso> ingresos { get; set; }
    }
}
